workflows:
  android-workflow:
    name: Android Build

    environment:
      flutter: stable

    scripts:
      - flutter clean
      - flutter pub get
      - flutter build apk --release || true
      - mkdir -p artifacts
      - find build -name "*.apk" -type f -exec cp {} artifacts/ \;
      - ls -R artifacts

    artifacts:
      - artifacts/*.apk
